name: example
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

# Add regular dependencies here.
dependencies:
  erc20:
    path: ../
  web3dart: ^3.0.0
  http: ^1.3.0

dev_dependencies:
  lints: ^5.1.0
  test: ^1.25.0
