name: erc20
description: Interface of the ERC20 standard as defined in the EIP-20 Token Standard.
version: 1.0.1
homepage: https://pwa.ir
repository: https://github.com/xclud/dart_erc20/

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  web3dart: ^2.5.2

dev_dependencies:
  test: ^1.22.0
  lints: ^2.0.0
  http: ^0.13.5
