name: erc20
description: Interface of the ERC20 standard as defined in the EIP-20 Token Standard.
version: 2.0.0
homepage: https://pwa.ir
repository: https://github.com/xclud/dart_erc20/

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  web3dart: ^3.0.0
  wallet: ^0.0.17

dev_dependencies:
  test: ^1.25.0
  lints: ^5.1.0
  http: ^1.0.0
